implement mihonapp/mihon#326
jobobby04/TachiyomiSY pull request #1104
Opened 2024-03-06 16:19 UTC by Shamicen

- Switched from the `Java` zip implementation to `Apache Commons Compresses`. 
- Archives are now being read from channels were applicable. 
- This PR includes the upstream fix mihonapp/mihon#485 which has not been merged as of now. 
- Removed usage of the `TempFileManager` were applicable

I also added a new option to load images into memory, in addition to the already existing options of reading them directly from the archive and caching the images to disk.

Credit for mihonapp/mihon#326 and mihonapp/mihon#485 goes to [FooIbar](https://github.com/FooIbar)

2024-03-14 17:18 UTC, jobobby04 requested changes
Looks good other then a nitpick 👍

2024-03-14 17:18 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/RarPageLoader.kt
> +        val semaphore = Semaphore(1)
`Semaphore(1)` is basically a `Mutex()`. I think it should use a Mutex if it needs to avoid multi-threading.

2024-03-14 17:18 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ZipPageLoader.kt
> +        val semaphore = Semaphore(1)
Same as other comment

2024-03-14 17:18 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/ui/reader/loader/ZipPageLoader.kt
> +        val semaphore = Semaphore(1)
Same as other comment

2024-03-16 00:34 UTC, jobobby04 commented
Looks like me cherry picking Mihon commits made conflicts, you can fix those and then I will merge 👍

2024-03-16 13:10 UTC, Shamicen commented
The remaining `detekt` detection `SerialVersionUIDInSerializableClass` was introduced by the upstream, we should wait and copy mihons fix.

2024-03-16 15:59 UTC, merged