Russian localization
jobobby04/TachiyomiSY pull request #215
Opened 2021-02-16 14:56 UTC by e-shl

2021-02-16 19:33 UTC, jobobby04 requested changes

2021-02-16 19:33 UTC, jobobby04 commented on app/src/main/res/values-ru/strings.xml
> +    <string name="pref_dual_page_split">Двойное разделение страниц (ALPHA)</string>
Can you remove the changes in this file? They are from Tachi main and I am planning on keeping these the same. If you want to translate them I suggest doing it through Weblate https://tachiyomi.org/help/contribution/#translation

2021-02-21 03:48 UTC, e-shl commented
what?

2021-02-21 03:53 UTC, jobobby04 commented
> 
> 
> what?

Move the SY specific translations(theme_dark_midnightdusk and theme_dark_red) from strings.xml to the strings_sy.xml. And remove the rest so that they are managed by Main tachiyomi. I am leaving strings.xml for main Tachi.

2021-02-21 04:25 UTC, e-shl commented
Made

2021-02-21 04:27 UTC, jobobby04 approved these changes

2021-02-21 04:29 UTC, jobobby04 commented
Thanks! I'll merge it before I release the next preview build.

2021-02-24 23:07 UTC, merged