Filter library by source
jobobby04/TachiyomiSY pull request #429
Opened 2021-09-30 12:03 UTC by simakover

Added option to filter library by sources

2021-10-03 22:23 UTC, jobobby04 requested changes
I am not sure if I will even merge this, you can already search by source so there isnt really a benefit. Otherwise here are my general comments on the PR

2021-10-03 22:23 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/data/preference/PreferencesHelper.kt
> +    fun filterSources(name: Int) = flowPrefs.getInt("${Keys.filterSource}_$name", ExtendedNavigationView.Item.TriStateGroup.State.IGNORE.value)
Dont use Int for the name, source id's should always be Long

2021-10-03 22:23 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +            Pair(it.id.toInt(), preferences.filterSources(it.id.toInt()).get())
I generally dont use the Pair constructor, use the `to` keyword like this
`it.id to preferences.filterSources(it.id).get()`
Also make sure to use Long's

2021-10-03 22:23 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibraryPresenter.kt
> +            val exclude = containsExclude.containsKey(item.manga.source.toInt())
Remove .toInt()

2021-10-03 22:23 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
> +            private val sourceFilters: Map<Int, Item.TriStateGroup>
Use a Long

2021-10-03 22:23 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/ui/library/LibrarySettingsSheet.kt
> +                        Pair(it.id.toInt(), Item.TriStateGroup(it.id.toInt(), this))
Refer to my other comment about pairs

2021-10-03 22:23 UTC, jobobby04 commented on app/src/main/java/eu/kanade/tachiyomi/widget/ExtendedNavigationView.kt
> +                    }
I wouldnt allow this, maybe make a different Holder for sources that returns the source name

2021-10-05 05:49 UTC, simakover commented
@jobobby04 made int- > long changes, but dont understand about holder. it is have same functionality, why and how make new?

2022-08-15 11:21 UTC, closed without merging